### ISSUE TITLE
Permission nodes not working

### ISSUE THREAD

**Issue by Foxzes** [arboriginal/PlayerRider#1] opened 2019-02-27 18:58 UTC
By default, without a config option to change it, players can ride and eject each other.

**Comment by arboriginal** [comment] 2019-02-27 19:53
(I've transferred this issue from NetherRoofBackFix project, because the issue tracker's link on Spigot page was wrong, my bad).

This is not a bug.

You can check permissions here:
https://github.com/arboriginal/PlayerRider/blob/master/src/plugin.yml#L22

playerrider.eject and playerrider.ride are default to true, so you have to negate them with your permissions manager plugin. For example, I'm using GroupManager and this is done by giving permissions "-playerrider.eject" and "-playerrider.ride" to players (permission name prefixed with a "-" symbol).

**Closed by arboriginal** 2019-02-27 19:53 UTC
